### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by ktym** [biohackrxiv/biohackrxiv.github.io#4]
In the FAQ,

> * What if I want to publish an update or follow up on a manuscript I already published in BioHackrXiv but that was developed outside a hackathon (e.g. offline collaborations)? Can I still publish it?
> 
>   * We restrict the publication of preprints in BioHackrXiv to material that has been initiated or developed during a BioHackathon-like event.

If this question intends to update the existing submission, it should be OK (as shown in the next FAQ).

Even if this would be the new submission of the continued work from the previous submission, it seems to be OK as the work "that has been initiated" during the BioHackathon-like event.

So, what kind of submissions do you want to reject here?

**Comment by ljgarcia** [comment]
From your comment, this question does not apply. Please remove it from the FAQ. Thanks.
