### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by ktym** [biohackrxiv/biohackrxiv.github.io#5]
> * Can I remove a preprint that was already published? (= withdraw my manuscript)
>   * Yes, you can do so but it is not an automatic/immediate process and requires approval by the Steering Committee.
  You can go to your submission list and then use the button "Withdraw", you must submit a reason to do so and then the
  Steering Committee will decide whether or not to approve it. You will be notified once a decision has been made.

What kind of considerations need to be made for the decision?

**Comment by ljgarcia** [comment]
I do not see a way to generalize this. It has to be analyzed on individual basis. That is why it is not up to moderators but to the whole Steering Committee.

**Comment by ktym** [comment]
Got it
